services:
    frontend:
        build:
            context: ./client
            dockerfile: Dockerfile
        image: sambasivachinta/exam-planner-client:latest
        environment:
            REACT_APP_SERVER_URL: "http://backend:8081"
        ports:
            - "3000:80"
        depends_on:
            - backend
    
    backend:
        build:
            context: ./server
            dockerfile: Dockerfile
        image: sambasivachinta/exam-planner-server:latest
        environment:
            PG_HOST: postgres
            PG_USER: samba
            PG_PASSWORD: s@mb@$!v@Ch!nt@123
            PG_DATABASE: app_db
            PG_PORT: 5432
            APP_PORT: 8080
        ports:
            - "8080:8080"
        depends_on:
            - postgres
    
    postgres:
        image: postgres:15
        container_name: postgres
        environment:
            POSTGRES_USER: samba
            POSTGRES_PASSWORD: s@mb@$!v@Ch!nt@123
            POSTGRES_DB: app_db
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
